# Generated by Django 4.1.3 on 2023-02-12 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(default=True, help_text="Выполнено ли дело"),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", models.TextField(blank=True)),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "due_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Плановое время завершения задачи",
                    ),
                ),
                (
                    "completed",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Фактическое время завершения задачи",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default="general",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="todolist.category",
                    ),
                ),
            ],
            options={"ordering": ["due_date"],},
        ),
    ]
